# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/LMAC3-vc7-9-2015-4/LMAC3-vc7-9-2015-4.srcs/sources_1/ip/fmac_rxfifo_ip_4Kx256/fmac_rxfifo_ip_4Kx256.xci
# IP: The module: 'fmac_rxfifo_ip_4Kx256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/LMAC3-vc7-9-2015-4/LMAC3-vc7-9-2015-4.srcs/sources_1/ip/fmac_rxfifo_ip_4Kx256/fmac_rxfifo_ip_4Kx256/fmac_rxfifo_ip_4Kx256.xdc
# XDC: The top module name and the constraint reference have the same name: 'fmac_rxfifo_ip_4Kx256'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/LMAC3-vc7-9-2015-4/LMAC3-vc7-9-2015-4.srcs/sources_1/ip/fmac_rxfifo_ip_4Kx256/fmac_rxfifo_ip_4Kx256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fmac_rxfifo_ip_4Kx256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/LMAC3-vc7-9-2015-4/LMAC3-vc7-9-2015-4.srcs/sources_1/ip/fmac_rxfifo_ip_4Kx256/fmac_rxfifo_ip_4Kx256.xci
# IP: The module: 'fmac_rxfifo_ip_4Kx256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/LMAC3-vc7-9-2015-4/LMAC3-vc7-9-2015-4.srcs/sources_1/ip/fmac_rxfifo_ip_4Kx256/fmac_rxfifo_ip_4Kx256/fmac_rxfifo_ip_4Kx256.xdc
# XDC: The top module name and the constraint reference have the same name: 'fmac_rxfifo_ip_4Kx256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/LMAC3-vc7-9-2015-4/LMAC3-vc7-9-2015-4.srcs/sources_1/ip/fmac_rxfifo_ip_4Kx256/fmac_rxfifo_ip_4Kx256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fmac_rxfifo_ip_4Kx256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
