# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.cache/wt [current_project]
set_property parent.project_path C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.7 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
set_property verilog_define {USE_DDR3_FIFO=1 USE_XPHY=1 USE_PVTMON=1} [current_fileset]
add_files -quiet C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/br_pre_ctrl_fifo_ip_1024x40_synth_1/br_pre_ctrl_fifo_ip_1024x40.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/br_pre_ctrl_fifo_ip_1024x40_synth_1/br_pre_ctrl_fifo_ip_1024x40.dcp]
add_files -quiet C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/br_pre_data_fifo_ip_1024x256_synth_1/br_pre_data_fifo_ip_1024x256.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/br_pre_data_fifo_ip_1024x256_synth_1/br_pre_data_fifo_ip_1024x256.dcp]
add_files -quiet C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/br_sfifo_ip_4x32_synth_1/br_sfifo_ip_4x32.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/br_sfifo_ip_4x32_synth_1/br_sfifo_ip_4x32.dcp]
add_files -quiet C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/pktctrl_fifo_ip_4kx32_synth_1/pktctrl_fifo_ip_4kx32.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/pktctrl_fifo_ip_4kx32_synth_1/pktctrl_fifo_ip_4kx32.dcp]
add_files -quiet C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/ipcs_fifo_ip_512x64_synth_1/ipcs_fifo_ip_512x64.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/ipcs_fifo_ip_512x64_synth_1/ipcs_fifo_ip_512x64.dcp]
add_files -quiet C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/fmac_rxfifo_ip_4Kx256_synth_1/fmac_rxfifo_ip_4Kx256.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/fmac_rxfifo_ip_4Kx256_synth_1/fmac_rxfifo_ip_4Kx256.dcp]
add_files -quiet C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/txfifo_ip_1024x256_synth_1/txfifo_ip_1024x256.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/txfifo_ip_1024x256_synth_1/txfifo_ip_1024x256.dcp]
add_files -quiet C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/x2c_bcnt_fifo_ip_256x32_synth_1/x2c_bcnt_fifo_ip_256x32.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/x2c_bcnt_fifo_ip_256x32_synth_1/x2c_bcnt_fifo_ip_256x32.dcp]
add_files -quiet C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/x2c_ctrl_fifo_ip_1024x32_synth_1/x2c_ctrl_fifo_ip_1024x32.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/x2c_ctrl_fifo_ip_1024x32_synth_1/x2c_ctrl_fifo_ip_1024x32.dcp]
add_files -quiet C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/x2c_data_fifo_ip_1024x256_synth_1/x2c_data_fifo_ip_1024x256.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC3-vc709-2015-4/hardware/vivado/runs/LMAC3-vc7-9-2015-4.runs/x2c_data_fifo_ip_1024x256_synth_1/x2c_data_fifo_ip_1024x256.dcp]
read_ip C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xci
set_property used_in_implementation false [get_files -all c:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xdc]
set_property is_locked true [get_files C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xci]

read_verilog -library xil_defaultlib {
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D56.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D96.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D16.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D168.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D128.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D160.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D216.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D120.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D256.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D24.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D64.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D152.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D112.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D224.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D192.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D32.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D104.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D232.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D184.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D144.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D72.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D88.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D48.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D200.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D136.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D240.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D208.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D176.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D248.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D80.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D8.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/CRCs/CRC32_D40.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/tx_mac10g_crc32x64.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/eth_crc32_gen.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/br_sfifo4x32.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/tx_encap_100G.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/tx_cgmii_LE2.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/tx_xgmii_LE2.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/tx_encap_10G.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/br_pre_ctrl_fifo1024x40.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/tx_10G_wrap.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/byte_reordering.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/s2p10.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/x2c_data_fifo1024x256.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/txfifo_1024x256.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/x2c_bcnt_fifo256x32.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/br_pre_data_fifo1024x256.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/rx_cgmii_LE2.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/fmac_fifo4Kx32.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/x2c_ctrl_fifo1024x32.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/fmac_rx_fifo4Kx256.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/tx_100G_wrap.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/rx_decap_LE2.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/fmac_ipcs_fifo512x64.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/rx_50G.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/x2c_ctrl.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/rx_100g.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/fmac_register_if_LE2.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/byte_reordering_wrap.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/tcore_fmac_core_LE2.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_CORE_TOP/LMAC_CORE_TOP.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/clock_control/clock_control_program.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/clock_control/kcpsm6.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LMAC_TOP_SYNTH/LMAC_TOP_SYNTH.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_RTL/LPBK_MODULE/LPBK_MODULE.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/network_path/network_path_shared.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/common/synchronizer_simple.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/clock_control/clock_control.v
  C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/hdl/LMAC3_vc709_2015_4.v
}
read_xdc C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/constraints/v7_LMAC3_base.xdc
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/constraints/v7_LMAC3_base.xdc]

read_xdc C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/constraints/v7_LMAC3_bit_rev1_0.xdc
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/constraints/v7_LMAC3_bit_rev1_0.xdc]

read_xdc C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/constraints/v7_LMAC3_xgemac_xphy.xdc
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/constraints/v7_LMAC3_xgemac_xphy.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top LMAC3_vc709_2015_4 -part xc7vx690tffg1761-2 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
write_checkpoint -noxdef LMAC3_vc709_2015_4.dcp
catch { report_utilization -file LMAC3_vc709_2015_4_utilization_synth.rpt -pb LMAC3_vc709_2015_4_utilization_synth.pb }
