# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/constraints/v7_LMAC3_base.xdc

# XDC: C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/constraints/v7_LMAC3_bit_rev1_0.xdc

# XDC: C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/constraints/v7_LMAC3_xgemac_xphy.xdc

# IP: C:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip_shared_logic_in_core || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip_shared_logic_in_core}]

# XDC: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip_shared_logic_in_core || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip_shared_logic_in_core}] {/inst }]/inst ]]

# XDC: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core_ooc.xdc

# XDC: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip_shared_logic_in_core || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip_shared_logic_in_core}] {/inst }]/inst ]]
