# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/LMAC3-vc7-9-2015-4/LMAC3-vc7-9-2015-4.srcs/sources_1/ip/x2c_bcnt_fifo_ip_256x32/x2c_bcnt_fifo_ip_256x32.xci
# IP: The module: 'x2c_bcnt_fifo_ip_256x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/LMAC3-vc7-9-2015-4/LMAC3-vc7-9-2015-4.srcs/sources_1/ip/x2c_bcnt_fifo_ip_256x32/x2c_bcnt_fifo_ip_256x32/x2c_bcnt_fifo_ip_256x32.xdc
# XDC: The top module name and the constraint reference have the same name: 'x2c_bcnt_fifo_ip_256x32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/LMAC3-vc7-9-2015-4/LMAC3-vc7-9-2015-4.srcs/sources_1/ip/x2c_bcnt_fifo_ip_256x32/x2c_bcnt_fifo_ip_256x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'x2c_bcnt_fifo_ip_256x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/LMAC3-vc7-9-2015-4/LMAC3-vc7-9-2015-4.srcs/sources_1/ip/x2c_bcnt_fifo_ip_256x32/x2c_bcnt_fifo_ip_256x32.xci
# IP: The module: 'x2c_bcnt_fifo_ip_256x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/LMAC3-vc7-9-2015-4/LMAC3-vc7-9-2015-4.srcs/sources_1/ip/x2c_bcnt_fifo_ip_256x32/x2c_bcnt_fifo_ip_256x32/x2c_bcnt_fifo_ip_256x32.xdc
# XDC: The top module name and the constraint reference have the same name: 'x2c_bcnt_fifo_ip_256x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/SUNNY2/LMAC3-vc709-2015-4/hardware/LMAC3-vc7-9-2015-4/LMAC3-vc7-9-2015-4.srcs/sources_1/ip/x2c_bcnt_fifo_ip_256x32/x2c_bcnt_fifo_ip_256x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'x2c_bcnt_fifo_ip_256x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
